SDIR=heatsrc
SOURCES_F=heat_mag.f90
MAIN_F=test.f90
SOURCESF=$(addprefix $(SDIR)/,$(SOURCES_F) $(MAIN_F))
FC=gfortran
EXECUTABLE=test_f

all: $(EXECUTABLE) $(SOURCESF)

$(EXECUTABLE): $(SOURCESF)
	$(FC) -o $@ $(SOURCESF)


.PHONY: clean

clean:
	rm -f $(SDIR)/*.o  $(EXECUTABLE)
